{
 "title": "Node",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"node.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\", mode!=\"idle\"}[5m]))",
     "legendFormat": "{{instance}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "{{instance}} - load"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job=~\"$job\", instance=~\"$instance\", fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\", instance=~\"$instance\"} - node_memory_MemFree_bytes{job=~\"$job\", instance=~\"$instance\"} - node_memory_Buffers_bytes{job=~\"$job\", instance=~\"$instance\"} - node_memory_Cached_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Free"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(irate(node_disk_reads_completed_total{instance=\"$instance\"}[5m]) or irate(node_disk_reads_completed{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} - {{device}}_read"
    },
    {
     "expr": "(irate(node_disk_writes_completed_total{instance=\"$instance\"}[5m]) or irate(node_disk_writes_completed{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} - {{device}}_write"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\"}",
     "legendFormat": "{{instance}} - established"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m]) or irate(node_network_receive_bytes{instance=\"$instance\"}[5m])) * 8",
     "legendFormat": "{{instance}} - {{device}}_in"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{instance=\"$instance\"}[5m]) or irate(node_network_transmit_bytes{instance=\"$instance\"}[5m])) * 8",
     "legendFormat": "{{instance}} - {{device}}_out"
    }
   ]
  }
 ]
}