{
 "title": "Queues",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"beanstalkd.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beanstalkd_up{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "beanstalkd_global_uptime{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "beanstalkd_global_current_connections{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "beanstalkd_tube_current_jobs_ready{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{tube}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beanstalkd_tube_current_jobs_ready{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{tube}}"
    }
   ]
  },
  {
   "title": "Jobs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beanstalkd_tube_total_jobs{job=~\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} - {{tube}}"
    }
   ]
  }
 ]
}