{
 "title": "Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "## Services" } },
  {
   "title": "SSL Certificate lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((probe_ssl_earliest_cert_expiry - time()) / 86400)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "options": { "content": "## Nodes" } },
  {
   "title": "UP web1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOAD web1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load" }
   ]
  },
  {
   "title": "MEMORY web1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job='node-exporter'} - node_memory_MemFree_bytes{job='node-exporter'} - node_memory_Buffers_bytes{job='node-exporter'} - node_memory_Cached_bytes{job='node-exporter'}) / node_memory_MemTotal_bytes{job='node-exporter'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK web1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job='node-exporter',fstype!='rootfs',mountpoint=\"/\"} / node_filesystem_size_bytes{job='node-exporter',mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 }, "options": { "content": "## Processes" } },
  {
   "title": "PROCESSES web1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pm2_up{job=\"pm2-exporter\",name!~\"stg-(.*)|pm2_(.*)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 }, "options": { "content": "## Databases" } },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mysql-exporter\"} / mysql_global_status_max_used_connections{job=\"mysql-exporter\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "MySQL Slow queries",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{job=\"mysql-exporter\"}[1m])",
     "legendFormat": "Utilization"
    }
   ]
  }
 ]
}