{
 "title": "Duplicati Backups",
 "tags": [
  "duplicati",
  "backups"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"duplicati.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "backup_name",
    "label": "Backup Name",
    "query": {
     "query": "label_values(duplicati_backup_status{job=~\"$job\", instance=~\"$instance\"}, backup_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Status",
   "type": "stat",
   "description": "Current status of all Duplicati backup jobs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicati_backup_status{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\"}",
     "legendFormat": "{{backup_name}} ({{machine_name}})"
    }
   ]
  },
  {
   "title": "Time Since Last Successful Backup",
   "type": "stat",
   "description": "Time since last successful backup",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by (backup_name, machine_name, job, instance) (duplicati_backup_timestamp{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\", status=\"1\"})",
     "legendFormat": "{{backup_name}} ({{machine_name}})"
    }
   ]
  },
  {
   "title": "Backup Status History",
   "type": "timeseries",
   "description": "Historical status of backup jobs over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "duplicati_backup_status{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\"}",
     "legendFormat": "{{backup_name}} ({{machine_name}})"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "timeseries",
   "description": "Duration of backup operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "duplicati_backup_duration_seconds{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\"}",
     "legendFormat": "{{backup_name}} ({{machine_name}})"
    }
   ]
  },
  {
   "title": "Files Included",
   "type": "timeseries",
   "description": "Number of files included in each backup",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "duplicati_backup_files_included{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\"}",
     "legendFormat": "{{backup_name}} ({{machine_name}})"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "timeseries",
   "description": "Size of backup data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "duplicati_backup_size_bytes{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\"}",
     "legendFormat": "{{backup_name}} ({{machine_name}}) - Original"
    },
    {
     "expr": "duplicati_backup_compressed_bytes{job=~\"$job\", instance=~\"$instance\", backup_name=~\"$backup_name\"}",
     "legendFormat": "{{backup_name}} ({{machine_name}}) - Compressed"
    }
   ]
  }
 ]
}