{
 "title": "Processes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"pm2.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pm2_up{job=~\"$job\",instance=~\"$instance\",name!~\"pm2-(.*)\"}) by (name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(pm2_cpu{job=~\"$job\",instance=~\"$instance\",name!~\"pm2-(.*)\"}) by (name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pm2_memory{job=~\"$job\",instance=~\"$instance\",name!~\"pm2-(.*)\"}) by (name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Restarts per week",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(pm2_restarts{job=~\"$job\",instance=~\"$instance\",name!~\"pm2-(.*)\"}[1w])) by (name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "pm2_uptime{job=~\"$job\",instance=~\"$instance\",name!~\"pm2-(.*)\"}",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  }
 ]
}