{
 "title": "Node",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Machine",
    "query": {
     "query": "up{job=\"node\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_export\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"node_export\",service=\"$service\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{service=~\"$service\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job='node_export',service='$service',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='node_export',service='$service'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='node_export',service='$service'} - node_memory_MemFree_bytes{job='node_export',service='$service'} - node_memory_Buffers_bytes{job='node_export',service='$service'} - node_memory_Cached_bytes{job='node_export',service='$service'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='node_export',service='$service'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='node_export',service='$service'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job='node_export',service='$service'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{service=~'$service'}[5m]) or irate(node_disk_reads_completed{service=~'$service'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{service=~'$service'}[5m]) or irate(node_disk_writes_completed{service=~'$service'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{service=~'$service'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{service=~'$service'}[5m])*8 or irate(node_network_receive_bytes{service=~'$service'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{service=~'$service'}[5m])*8 or irate(node_network_transmit_bytes{service=~'$service'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  }
 ]
}