{
 "title": "Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ynni.energy: Days untill SSL expires",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((probe_ssl_earliest_cert_expiry{job=\"blackbox\",instance=\"ynni.energy\"} - time()) / 86400)"
    }
   ]
  },
  {
   "title": "ynni-living-lab.wittigdemo.nl: Days untill SSL expires",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((probe_ssl_earliest_cert_expiry{job=\"blackbox\",instance=\"ynni-living-lab.wittigdemo.nl\"} - time()) / 86400)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UP",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_up{device=\"ens5\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "UP service MySQL",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job='node_export',fstype!='rootfs',mountpoint=\"/\"} / node_filesystem_size_bytes{job='node_export',mountpoint=\"/\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "LOAD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load" }
   ]
  },
  {
   "title": "MEMORY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job='node_export'} - node_memory_MemFree_bytes{job='node_export'} - node_memory_Buffers_bytes{job='node_export'} - node_memory_Cached_bytes{job='node_export'}) / node_memory_MemTotal_bytes{job='node_export'}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mysql\"} / 151",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "MySQL Slow queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{job=\"mysql\"}[1m])",
     "legendFormat": "Utilization"
    }
   ]
  }
 ]
}